### ISSUE TITLE
Unable to build with Ubuntu 16.04.3

### ISSUE THREAD

**Issue by bw2012** [zcoinofficial/sgminer#1]
Hi
I cannot build current version with Ubuntu 16.04.3
It looks like build system tries to compile *.hpp files with GCC
What I can change in configure.ac and Makefile.am to solve it?

```
In file included from merkletree/mtp.h:16:0,
                 from miner.h:18,
                 from sgminer.c:55:
merkletree/merkle-tree.hpp:4:8: error: expected identifier or ‘(’ before string constant
 extern "C" {
        ^
merkletree/merkle-tree.hpp:8:18: fatal error: vector: No such file or directory
compilation terminated.
```

**Comment by djm34** [comment]
should work now

**Comment by serega-kl** [comment]
Hi djm34

Still can't compile

`sgminer-algorithm.o: In function `queue_mtp_kernel2':
algorithm.c:(.text+0x3524): undefined reference to `mtp_solver_short'
collect2: error: ld returned 1 exit status
Makefile:933: recipe for target 'sgminer' failed
make[2]: *** [sgminer] Error 1`

Or maybe you can upload pre-compiled version?

**Comment by djm34** [comment]
you know it isn't a "still", it is a new problem

**Comment by djm34** [comment]
ok I fixed the compilation problem, redownload the source, it should work now
